### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by chienminh5298** [Mr-Un1k0d3r/DKMC#17]
Hi guys, i'm try to installing dkmc.py with command "python dkmc.py" but i receipt this issue
![image](https://user-images.githubusercontent.com/40522121/42837782-363c1e72-8a29-11e8-9d61-361cb2775c9c.png)

**Comment by Mr-Un1k0d3r** [comment]
Seems like your version of pythin was installed / compiled without the --with-ssl switch

**Comment by chienminh5298** [comment]
How to fix that ? Pls ?
