### ISSUE TITLE
error while starting dkmc.py

### ISSUE THREAD

**Issue by GetRektBoy724** [Mr-Un1k0d3r/DKMC#21]
root@nobody:~/DKMC# python dkmc.py
Traceback (most recent call last):
  File "dkmc.py", line 2, in <module>
    from core.ui import UI
ImportError: No module named core.ui
root@nobody:~/DKMC#

**Comment by Mr-Un1k0d3r** [comment]
seems like you may have some file missing try to run git pull or download it again.

**Comment by GetRektBoy724** [comment]
ohh thank you very much
