### ISSUE TITLE
I REMAKE YOUR TOOL!!!

### ISSUE THREAD

**Issue by GetRektBoy724** [Mr-Un1k0d3r/DKMC#22]
SEE AT github.com/GetRektBoy724/DKMCPRO

**Comment by Mr-Un1k0d3r** [comment]
So far based on what I saw you stole the tool. The only change you made consisted of changing the author name.

**Comment by GetRektBoy724** [comment]
its been a long time im not updating my DKMCPRO repositories now its until version 3.7
