### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pparker1800** [Mr-Un1k0d3r/DKMC#29]
File "dkmc.py", line 12
    os.makedirs("output/")

with or without 'output' place.

**Comment by wsiff** [comment]
This is due to difference in indentation. Easiest solution:

pip install autopep8
then move to DKMC directory,
autopep8 -i dkmc.py

It'll do the trick.

**Comment by Mr-Un1k0d3r** [comment]
fixed the code indentation
