### ISSUE TITLE
proxy aware PS payload

### ISSUE THREAD

**Issue by miskovv** [Mr-Un1k0d3r/DKMC#9]
First of all, great tool! Really enjoy using this. 

When the victim end device is using a proxy for outgoing traffic, the powershell payload to download the image fails:
Exception calling "DownloadData" with "1" argument(s): "The external server returned an error: (407) Proxy verification is needed."

Do you have any plans of implementing an option to make the powershell payload proxy-aware?
I really would really like to see this option in the PS payload generator, something like: 

[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials

In order to use the users default proxy credentials. I'm not aware of a trigger that can set this option from a powershell one liner.

**Comment by Mr-Un1k0d3r** [comment]
good point I should add it to the payload
